### ISSUE TITLE
no results even for local completions

### ISSUE THREAD

**Issue by elia** [rsense/rsense#23]
basically what I'm doing is this:

``` bash
curl -s -X POST -H Accept:\ application/json -H Content-Type:\ application/json --data @/tmp/rsense.json http://localhost:47367 
```

_rsense.json_

``` json
{"command":"code_completion","project":"/Users/elia/Code/foo","file":null,"code":"class Aasdfasfdasfdas\n  \nend\n\nAa","location":{"row":6,"column":4}}
```

Nothing changes even if `file:` is not seto to `null`

**Comment by edubkendo** [comment]
This is because rsense [injects a node into the AST](https://github.com/rsense/rsense-server/blob/master/lib/rsense/server/code.rb) to do pretty much anything.  Then when it walks the AST,  and [hits that call node](https://github.com/rsense/rsense-core/blob/master/src/org/cx4a/rsense/typing/Graph.java#L813) it triggers it to [call a special method](https://github.com/rsense/rsense-server/blob/master/lib/rsense/server/command/type_inference_method.rb#L16) on the node prior to it via [this mechanism in the RuntimeHelper](https://github.com/rsense/rsense-core/blob/master/src/org/cx4a/rsense/typing/runtime/RuntimeHelper.java#L577). 

(For the record, that mechanism is the typical way to extend rsense, for instance I've added some special methods to handle `native_accessor` and `alias_native` from Opal's Native module. Basically, you teach it to recognize new strings in the AST.  In the case of `__rsense_type_inference__` it happens to be a string rsense has injected itself, but it also uses it for `require`, `new` and other inherent ruby syntax).

So, it's basically designed to do completion at points where you would type a `.` or `::`.  I've been thinking a long time about a better way to do this and I have an idea, but I don't think it would actually make this work. These kind of completions should work though, so I'll have to think some more about it.
