### ISSUE TITLE
Windows 10 fails to launch

### ISSUE THREAD

**Issue by tan-wei** [rsense/rsense#45]
Version:
- Windows 10
- Ruby 2.5.5p157 (2019-03-15 revision 67260) [i386-mingw32]
When exec `rsense start --port 47367`, it fails:
```
Traceback (most recent call last):
        3: from C:/Ruby25/bin/rsense:23:in `<main>'
        2: from C:/Ruby25/bin/rsense:23:in `load'
        1: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rsense-0.5.18/bin/rsense:12:in `<top (required)>'
C:/Ruby25/lib/ruby/gems/2.5.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoon::FileActions (NameError)
Did you mean?  FileUtils
```

Anyway, does the project still active?

**Comment by jonyyz** [comment]
The reason for this issue is Spoon doesn't support Windows.  rsense should consider using a different approach because it doesn't look like Spoon gets much attention.  Or if someone is capable, submit a PR to Spoon for proper Windows support.  I asked the current maintainer of Spoon to at least raise an error indicating that Windows is not supported as opposed to some esoteric error message.

**Comment by tan-wei** [comment]
Got it. Thanks for your reply.
